AllCops:
  NewCops: disable

Style/Documentation:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Metrics/AbcSize:
  Max: 50

Style/NegatedIf:
  EnforcedStyle: postfix