AllCops:
  NewCops: disable

Style/Documentation:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma


Style/NegatedIf:
  EnforcedStyle: postfix